package com.suspringboot.frame.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.id
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.account_id
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private String account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.name
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.token
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.gmt_create
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private Long gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.gmt_modified
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private Long gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.bio
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frameuser.avatar_url
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    private String avatar_url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.id
     *
     * @return the value of frameuser.id
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.id
     *
     * @param id the value for frameuser.id
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.account_id
     *
     * @return the value of frameuser.account_id
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public String getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.account_id
     *
     * @param account_id the value for frameuser.account_id
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setAccount_id(String account_id) {
        this.account_id = account_id == null ? null : account_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.name
     *
     * @return the value of frameuser.name
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.name
     *
     * @param name the value for frameuser.name
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.token
     *
     * @return the value of frameuser.token
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.token
     *
     * @param token the value for frameuser.token
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.gmt_create
     *
     * @return the value of frameuser.gmt_create
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.gmt_create
     *
     * @param gmt_create the value for frameuser.gmt_create
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.gmt_modified
     *
     * @return the value of frameuser.gmt_modified
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.gmt_modified
     *
     * @param gmt_modified the value for frameuser.gmt_modified
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.bio
     *
     * @return the value of frameuser.bio
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.bio
     *
     * @param bio the value for frameuser.bio
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frameuser.avatar_url
     *
     * @return the value of frameuser.avatar_url
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public String getAvatar_url() {
        return avatar_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frameuser.avatar_url
     *
     * @param avatar_url the value for frameuser.avatar_url
     *
     * @mbg.generated Tue Jan 07 17:53:24 CST 2020
     */
    public void setAvatar_url(String avatar_url) {
        this.avatar_url = avatar_url == null ? null : avatar_url.trim();
    }
}